services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="2354@Krishna"
      - MYSQL_DATABASE="library_db"
  
  webapp:
    build: .
    image: library_management_system
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - DB_NAME="library_db"
      - DB_USER=root
      - DB_PASSWORD="2354@Krishna"
      - DB_HOST=database
      - DB_PORT=3306
    
    
