services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=2354@Krishna
      - MYSQL_DATABASE=library_db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'2354@Krishna'"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
  
  webapp:
    build: .
    image: library_management_system
    depends_on:
        database:
          condition: service_healthy
    ports:
      - "8000:8001"
    environment:
      - DB_NAME=library_db
      - DB_USER=root
      - DB_PASSWORD=2354@Krishna
      - DB_HOST=database
      - DB_PORT=3306
    
    
